application:
  title: 'AES Encrypt/Decrypt Tool'
  version: '1.0.0'
spring:
  main:
    banner-mode: 'OFF'
  config:
    import:
      - secret.yml
logging:
  level:
    root: ERROR
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss.SSS}] %-5level ${PID:-} [%8.8thread] %-30.30logger{30} : %msg%n"
